version: "3.1"

services:
  hobanialauncher:
    container_name: Hobanialauncher
    restart: always
    image: registry.gitlab.com/hobania/hobanialauncher/server:master
    volumes:
      - "./data:/opt/app/data"
      - "./config:/opt/app/config"
    environment:
      - RUST_LOG=info,server=debug
      - ROCKET_ENV=production
    ports:
      - "8000:8000"
